version: '3.8'

services:
  foundry-v13:
    image: felddy/foundryvtt:release
    container_name: foundry-v13
    ports:
      - "30013:30000"
    volumes:
      - foundry_data_v13:/data
    restart: unless-stopped

  builder:
    image: node:20-alpine
    container_name: foundry-builder
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    restart: unless-stopped

volumes:
  foundry_data_v13: